export const DemoData = [
    {        id:'p1' , name: 'Demo 1', price: '500',    },
    {        id:'p2' , name: 'Demo 2', price: '500',    },
    {        id:'p3' , name: 'Demo 3', price: '500',    },
    {        id:'p4' , name: 'Demo 4', price: '500',    },
    {        id:'p5' , name: 'Demo 5', price: '500',    },
    {        id:'p6' , name: 'Demo 6', price: '500',    },
    {        id:'p7' , name: 'Demo 7', price: '500',    },
    {        id:'p8' , name: 'Demo 8', price: '500',    },
    {        id:'p9' , name: 'Demo 9', price: '500',    },
    {        id:'p10' , name: 'Demo 10', price: '500',    },
    {        id:'p10' , name: 'Demo 10', price: '500',    },
    {        id:'p10' , name: 'Demo 10', price: '500',    },
    {        id:'p10' , name: 'Demo 10', price: '500',    },
    {        id:'p10' , name: 'Demo 10', price: '500',    },
    {        id:'p10' , name: 'Demo 10', price: '500',    },
    {        id:'p10' , name: 'Demo 10', price: '500',    },
    
]
export const CartData = [
    {        id:'c1',name: 'Cart Product 1', price: '560',   amt:'1'   },
    {        id:'c2',name: 'Cart Product 2', price: '600' , amt: '2'   },
    {        id:'c3',name: 'Cart Product 3', price: '250' , amt: '3'   },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },
    {        id:'c4',name: 'Cart Product 4', price: '50' ,  amt: '4'  },

]